### ISSUE TITLE
Clarify use of motion masks

### ISSUE THREAD

**Issue by ericearl** [ABCD-STUDY/nda-abcd-collection-3165#1]
Make it clear how the MATLAB motion masks are generated and used, especially in regard to the first "skipped/censored" frames.

**Comment by audreymhoughton** [comment]
Need to describe what is happening in the first frames - exclude the first ~5 frames for dummy frames. (get actual number)
- what was used for thresholding for initial params

**Comment by LuciMoore** [comment]
This is described in [Adolescent Brain Cognitive Development (ABCD) Community MRI Collection and Utilities](https://www.biorxiv.org/content/10.1101/2021.07.09.451638v1) - I'll make sure this is included in the RTDs although it surely is already
