### ISSUE TITLE
Questions about motion-corrected individual functional task run in MNI space in a volume

### ISSUE THREAD

**Issue by tommyng730** [ABCD-STUDY/nda-abcd-collection-3165#10]
Hello,

I'm wondering what specific preprocessing steps have been applied to the motion-corrected files in volume space (sub-#/ses-#/func/sub-#_ses-#_task-(MID|nback|SST|rest)_run-#_space-MNI_bold.nii.gz). For example, did these images undergo Advanced Normalization Tools (ANTs) and DCANBOLDProcessing (DBP)? Thank you so much for your time!

**Comment by ericfeczko** [comment]
HI Tommyng730!  

The volume space files have been normalized to the MNI space (i.e. distortion correction, motion-correction, atlas registration). DCAN BOLD processing was not run on the data. Effectively, these images are output from fMRIVolume (see here: for more details https://collection3165.readthedocs.io/en/stable/pipeline/#stage-4-fmrivolume).

Please let us know if you have any further questions, thanks!
