### ISSUE TITLE
2 year follow-up MRI data

### ISSUE THREAD

**Issue by MartinGell** [ABCD-STUDY/nda-abcd-collection-3165#11]
Hi,

Your current data release only contains the initial/baseline MRI (and fMRI) assessment of 9-10 year olds, is that correct? If so, are you also planning to release at some point the 2nd year follow-up data (MRI and fMRI) that are available in the ABCD release 3.0 on NDA (https://nda.nih.gov/study.html?id=901)? Trying to figure out which data are best for us to download and use.

Thanks!

Martin

**Comment by kasbohm** [comment]
Hi, came here to ask the same question.
Wondering if I should wait for a BIDS release or fetch the source files from the 3.0 release. 

Thanks a lot!

**Comment by ericfeczko** [comment]
Hi there! 

Great question! 

Yes, we are planning ongoing releases for the Year 2 data and beyond. We are currently in the process of preparing the Year 2 data for processing (ABCD 3.0 and 4.0), and anticipate having the data ready by summer.
