### ISSUE TITLE
Association between minimally processed ABCD data vs. DCAN Lab processing

### ISSUE THREAD

**Issue by seonjoo** [ABCD-STUDY/nda-abcd-collection-3165#12]
It seems that the fMRI processing started from the scratch, not the minimally processed data that are provided by the ABCD MRI core. So DCAN Lab data do not follow any of the steps that the minimally processed data did? And all steps are very different? Here's the steps that were listed in NDA 3.0 Resting-State Functional Magnetic Resonance Imaging.docx. 

●	head motion corrected by registering each frame to the first using AFNI’s 3dvolreg (Cox, 1996)
●	B0 distortions were corrected using the reversing gradient method with FSL’s TOPUP (Andersson et al., 2003, Smith et al., 2004)
●	displacement field estimated from spin-echo field map scans
●	applied to gradient-echo images after adjustment for between-scan head motion
●	corrected for gradient nonlinearity distortions (Jovicich, et al., 2006)
●	between scan motion correction across all fMRI scans in imaging event
●	registration between T2-weighted, spin-echo B0 calibration scans and T1-weighted structural images performed using mutual information (Wells, et al., 1996)
 
Thank you so much.

**Comment by ericfeczko** [comment]
Hi Seonjoo,

This is correct. The ABCD-3165 collection contains derived data from the ABCD-BIDS pipeline. ABCD-BIDS is an HCP-style pipeline specifically modified to work across multiple acquisitions. This pipeline is very different from the tabulated data from the DAIRC.

More information about the pipeline can be found here: https://collection3165.readthedocs.io/en/stable/pipeline/

We will be releasing a preprint shortly that explains all this in greater detail, so stay tuned, and please continue to ask any questions you might have. We also have other outputs available upon request, so don't hesitate to post requests for new features as well!

-Eric

**Comment by seonjoo** [comment]
Thank you so much for the clarification.
