### ISSUE TITLE
Matched groups - what is group 3?

### ISSUE THREAD

**Issue by traceyshi** [ABCD-STUDY/nda-abcd-collection-3165#13]
We are interested in the matched groups of participants that you have created (https://collection3165.readthedocs.io/en/stable/recommendations/#2-the-bids-participants-files-and-matched-groups) but wanted to clarify about Group 3, which is much smaller than Groups 1-2 and not included in the description of the matching. Are the participants in Group 3 intentionally excluded from the main groups? (and if yes, is this based on data quality? other metrics?) Or is there some other reason for their assignment to Group 3? Thanks!

**Comment by arueter1** [comment]
Thanks for your question! We will get back to you with an answer soon.

**Comment by ericfeczko** [comment]
Good question! 
Group 3 is used as a high-quality held-out sample for the purpose of creating templates for other approaches (e.g. template matching networks). This is done to reduce the chances of data leakage with Groups 1 and 2. The data themselves are in fact, quite usable, and can serve as a good sandbox for model tuning or feature selection.

Group1 and Group2 are extremely well matched, so I would recommend using them for reproducibility/testing. Hope this helps!

-Eric Feczko
