### ISSUE TITLE
Processing done to MNI functional time series

### ISSUE THREAD

**Issue by gsudre** [ABCD-STUDY/nda-abcd-collection-3165#14]
Hi! I was wondering if the DCANBoldProc step has been applied to the _space-MNI_bold.nii.gz files as well, or only the _desc-filtered_timeseries.dtseries.nii files. The former only says "Motion corrected" in their description, so I was wondering if the main filtering/motion censoring steps in DPB had been applied for the voxelwise data in MNI space. Thanks!

**Comment by arueter1** [comment]
Thanks for your question! We will get back to you soon.

**Comment by ericfeczko** [comment]
Hi @gsudre!
To clarify, voxelwise files have not been run through DPB, which only operates on CIFTI files. The "motion corrected" refers to the frame-wise realignment. Thanks for asking!

-Eric
