### ISSUE TITLE
Atlas space for dtseries

### ISSUE THREAD

**Issue by seonjoo** [ABCD-STUDY/nda-abcd-collection-3165#18]
For the minimally processed fMRI data, I can see 

sub-*_ses-baselineYear1Arm1_task-*_bold_desc-filtered_timeseries.dtseries.nii

And it says that 
"Concatenated functional task dense time series post-DCANBOLDProcessing (regression and filtering) in Atlas space."

What does the Atlas space mean? Is it in MNI space? If I want to use Cole's Atlas (with subcortical parcellation in MNI space) is it correct way to extract parcels?

**Comment by arueter1** [comment]
Hi There! Thanks for the question! We will get back to you with an answer as soon as possible.

**Comment by ericfeczko** [comment]
Hi Seonjoo!

My apologies for the late reply. The file is encoded in a CIFTI format, where the volumetric space is MNI, and the surface space is the fsaverage_LR32k ( an excellent "unofficial" explanation of the format can be found [here](https://emmarobinson01.com/2016/02/10/unofficial-guide-to-the-hcp-surface-file-formats/), and see [here](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3720813/) for the associated manuscript on the associated formats). Briefly, the surface space is the freesurfer average template with the left and right hemispheres mirrored. Each hemisphere contains 32,000 vertices -- including the medial wall. 

The [workbench](https://www.humanconnectome.org/software/connectome-workbench) command cifti-separate can be used to split CIFTI files into GIFTI surface files and a volumetric subcortical file. The volumetric file for the dtseries here will contain the functional MRI timeseries data mapped to the FSL 2006 MNI template. These files will also be quite large.

An alternative is to use workbench to [create a label file](https://www.humanconnectome.org/software/workbench-command/-cifti-create-label) from the volumetric ROI. To do so, you'll need to check whether Cole's ROIs can be mapped to one of 19 subcortical structures indexed within the CIFTI. Such a label file can easily contain multiple labels. Afterwards, the -cifti-parcellate command can be used to extract a parcellated time-series per label within the label file.

Hope this helps!
