### ISSUE TITLE
Question regarding preprocessing/denoising of fmri derivatives

### ISSUE THREAD

**Issue by sidchop** [ABCD-STUDY/nda-abcd-collection-3165#19]
Hi,

First, thanks for this amazing resource. 

I had a question regarding the pre-processing/denoising of the filtered_timeseries derivatives. I understand that the data undergo additional preprocessing beyond minimally preprocessed data, and the DCAN preprocessing program is used for this. The [preprint](https://www.biorxiv.org/content/10.1101/2021.07.09.451638v1.full#F1) outlines that a filtering process for the motion estimates was applied, and these filtered motion estimates were then regressed out. I wanted to confirm that no other denoising such as regression of wm/csf, bandpass filtering, detrending or volume censoring was applied to the derivatives?

For context, we are trying to assess where the preprocessing and denoising of fmri data used in the [brain-wide association](https://www.biorxiv.org/content/10.1101/2020.08.21.257758v1.full.pdf) paper are identical to derivatives provided here. 

Thanks!

**Comment by arueter1** [comment]
Thanks for your question! @ericfeczko will be able to answer this for you soon.

**Comment by sidchop** [comment]
Hi - I found the answer in the [provided docs](https://collection3165.readthedocs.io/en/stable/pipeline.html#stage-6-dcanboldprocessing-dbp) - thanks!

**Comment by arueter1** [comment]
Great! I'm glad the documentation helped! Please let us know if you have any additional questions.
