### ISSUE TITLE
Add exact commands used to run data

### ISSUE THREAD

**Issue by ericearl** [ABCD-STUDY/nda-abcd-collection-3165#21]
It would be good to add the exact commands used to prep the data in the collection through the abcd-dicom2bids, the abcd-hcp-pipeline, and the functional connectivity code (for the connectivity matrices).  This way not only are the repositories existent, but good example commands are existent and repeatable here too.

**Comment by arueter1** [comment]
Thanks @ericearl. Are you suggesting that the exact commands are listed in this repo or that they are documented in the readthedocs?

**Comment by ericearl** [comment]
Yes, the readthedocs, thanks!

**Comment by arueter1** [comment]
Sounds good! We will work to add that after this round of uploads. It won't be a high priority item, but we will hopefully get this in there by the end of the year.

**Comment by arueter1** [comment]
@ericearl do you have the exact commands on hand that you would like inserted into the documentation? That would help us add this into the ReadTheDocs more easily.

**Comment by ericearl** [comment]
@arueter1 No, I don't have any handy.  My recommendation is to get the commands or scripts which Audrey or Tim or Anders use to convert with abcd-dicom2bids, process with abcd-hcp-pipeline, and prep the connectivity data.  Sort of a "how it was done" record all the way down to the command line or scripts.

**Comment by ericfeczko** [comment]
All good -- we have them and we'll update as part of a broader set of revisions ;)

**Comment by ericearl** [comment]
Sounds good!  Maybe even just a "abcd_processing_utilities" repository you reference in the readthedocs might be enough.

**Comment by audreymhoughton** [comment]
We are intending to make a general slurm/s3 repository in the future. This issue will be answered when that repository is available.

**Comment by LuciMoore** [comment]
we are moving away from using the NDA, so will not be maintaining this repository anymore in the near future
