### ISSUE TITLE
Same participants in different sites

### ISSUE THREAD

**Issue by zhangjb35** [ABCD-STUDY/nda-abcd-collection-3165#22]
Hi,
I get the `participants_v1.0.0.zip` from NDA (https://nda.nih.gov/edit_collection.html?id=3165). After comparing it with the sites info provided by ABCD package, seem some participants with the wrong sites info for baseline measurement.

for example,
"sub-NDARINVXXXXXXXX"	"ses-baselineYear1Arm1"	"1"	"site17"	....
"sub-NDARINVXXXXXXXX"	"ses-baselineYear1Arm1"	"1"	"site11"	....
(this is from participants.tsv)

NDAR_INVXXXXXXXX,site11,... (this subject have multiple sites at the follow up measurement)
(this is from ABCD)

**Comment by arueter1** [comment]
Hi @Jinboasltw - thanks so much for bringing this to our attention. I'm going to delete the subID information from this post because it is PHI for this study. I have assigned some folks from our lab, and we will get back to you as soon as possible with answers/actions.

Thanks! Happy Holidays!

**Comment by zhangjb35** [comment]
Thanks. Sorry for ignoring the risk to show the full ID in the post. I just want to give some direct examples.

**Comment by rosemccollum** [comment]
We need to verify that this information actually has been updated. If not, it should be updated in the new participants.tsv we are uploading soon.

**Comment by lundq163** [comment]
Hi @Jinboasltw, we just uploaded the new participants.tsv to the collection on the NDA. This version should include the necessary fixes you had outlined in this issue. If you continue to encounter the issue though, please reopen this and we will get it addressed. Thanks for your patience!
