### ISSUE TITLE
Do "Scanner Differences" in ABCC processing control for manufacturer effects?

### ISSUE THREAD

**Issue by kimberlylray** [ABCD-STUDY/nda-abcd-collection-3165#24]
Hello ABCC team, 
Thank you so much for providing this invaluable community resource. 
I am using the ABCC resting state data and am wondering how much the '[scanner differences](https://collection3165.readthedocs.io/en/stable/inputs/#6-scanner-differences)' preprocessing step in the Collection 3165 - ABCD-BIDS Community Collection (ABCC) documentation controls/reduces the manufacturer effects observed in [Marek et al., 2019](https://www.sciencedirect.com/science/article/pii/S1878929319302932?via%3Dihub). Or are these effects still present and need to be accounted for  in the ABCC? 
Thank you!

**Comment by ericfeczko** [comment]
We try to minimize differences as much as possible, but keep in mind that MRI acquisition remains fundamentally different between GE, Siemens, and Philips platforms. As a result, I highly recommend checking and controlling for manufacturer effects in subsequent analyses.
