### ISSUE TITLE
Request to contribute derived stop-signal task model parameter data

### ISSUE THREAD

**Issue by aweigard** [ABCD-STUDY/nda-abcd-collection-3165#25]
Hi ABCC Team,

First of all, thank you so much for your hard work on developing this excellent, and much needed, resource for lateral data sharing!

I am hoping to contribute data derived from the ABCD stop-signal task to ABCC. These data consist of parameter estimates from the computational model we outline in our recent bioRxiv preprint (https://www.biorxiv.org/content/10.1101/2021.07.26.453872v1.abstract) that addresses key measurement concerns related to the stop-signal task design. We have already shared our code for estimating parameters from this model (https://osf.io/2h8a7/) but, as we recognize that the code is resource-intensive and difficult to use for those without a background in Bayesian estimation, we are hoping to share full posterior distributions of model parameters, as well as more easy-to-use point estimates, for participants in the entire ABCD sample. We are planning on simultaneously posting a revision to the bioRxiv preprint that directs interested users to ABCC to obtain these parameter estimates.

Based my reading of your recent preprint, I understand that posting an issue on this page is the first step towards initiating the review and approval process. If you could please let me know what additional steps I need to take to complete this process, I would really appreciate your help. 

Thank you, again,
Alex Weigard

**Comment by ericfeczko** [comment]
Hey @aweigard !

My apologies for the excessively late reply. I would be delighted to help with this, if you could email me at feczk001@umn.edu -- I would be more than happy to help get you started.

**Comment by audreymhoughton** [comment]
@aweigard - I am going to close this issue, assuming that you reached out to Fez via email to contribute. Please re-open this issue if you still have questions.
