### ISSUE TITLE
Access to Year 2 Follow-up DTI and T1 data 

### ISSUE THREAD

**Issue by eliacello** [ABCD-STUDY/nda-abcd-collection-3165#26]
ABCC only has baseline data. I would like to download both baseline and Year 2 follow-up which prevents me to use the nda-abcd-s3-downloader tool. I turned back to the abcd-dicom2bids tool but it does not recognise my NDA username and password 'Failed to create NDA token using the username and decrypted password from /home/eb07/.abcd2bids/config.ini.' The ndar_awskeys.txt file isn't generated. Any idea of what could be the problem here? Alternatively, what would be the best way to transform DICOM to BIDS for both baseline and Year 2 follow up fast-track ABCD images? 
Many thanks.

**Comment by arueter1** [comment]
HI @eliacello - Thanks for your email! We are currently processing the Year 2 data for the ABCC and will upload to the NDA as soon as we are able. There were some unforeseen challenges as the ABCC collection is curated to use data that has passed on the Fast Track QC document and we were waiting for updates (updates are still ongoing, so there will likely be future changes as well). 

Which of the following paths would be best for you?
(1) Wait for our next release as it will be the correct data according to the Fast-Tracked ABCD QC. 
(2) Start processing these data yourself. If you would like to do all of this processing yourself, I have assigned some folks from our lab to see if they have insights about the NDA token errors.

**Comment by eliacello** [comment]
Hi @arueter1 , Thank you so much for your quick response. I guess it must be difficult to estimate but will the next release occur in 2 or more 8 months? In the latter case I  will be willing to try to start processing myself because of time constraints. I am only working with a small subset of participants (~1500) so hopefully, it won't be too time-consuming to check their QC status..? @perronea, it would be great to have your input on the issue I encounter with NDA token generator when I use the abcd-dicom2bids. Thank you very much for you help!

**Comment by arueter1** [comment]
Hi @eliacello - We just got an updated Fast Track QC document this week with significantly more Year 2 data QC'ed. This changes our trajectory and timelines. I am guessing that we will not have our next release uploaded to the NDA for 3 months. The NDA needs to QC the upload before it is released publicly, which can take anywhere from 1-5 months (hopefully the shorter timeframe)! Given that information, I do not think we will have our next release out for 4-8 months. I hope this is helpful for you to make decisions that work best for you!

I am going to close this ticket. If you have further issues with the NDA token generator, please create an issue on the applicable repo: https://github.com/ABCD-STUDY/abcd-dicom2bids/issues
