### ISSUE TITLE
Detailed processing information of *_task-*_run-*_space-MNI_bold.nii.gz images

### ISSUE THREAD

**Issue by seonjoo** [ABCD-STUDY/nda-abcd-collection-3165#28]
Dear ABCD-STUDY Team,
Form the ABCD 3165 (DCAN-lab processing collection), I found there's 4D volume images with the description of motion corrected. 

Can I know the detailed information of how far this images were processed?
Thank you.
-Seonjoo

**Comment by arueter1** [comment]
Hi Seonjoo - apologies for the late response. All of the information can be found on this website: https://collection3165.readthedocs.io/en/stable/

In particular, processing pipelines are explained in more detail here: https://collection3165.readthedocs.io/en/stable/pipeline/

If further information is needed, please let us know if you have any further questions. Closing this issue for now.
