### ISSUE TITLE
availability of xfms and other HCP Pipeline intermediates

### ISSUE THREAD

**Issue by elyb01** [ABCD-STUDY/nda-abcd-collection-3165#3]
Hi, these pipelines and the already preprocessed dataset are amazing resources, thank you all so much for putting this out there! I'm still new to the collection, but it looks like the subject-level HCP-Pipeline-style data available through NDA are limited to:

1) anatomical midthickness surfaces (native+MNI @ 32k+164k)
2) anatomical CIFTI outputs (curvature, thickness, sulcal depth, myelin maps)
3) the ACPC-aligned native-space anatomical segmentation from FreeSurfer's Desikan-Killiany atlas (aparc+aseg)
4) fMRI dense timeseries CIFTIs and associated movement parameters
5) fMRI parcellated timeseries CIFTIs created using the Gordon/HCP/Markov/Power/Yeo parcellations

Is it possible to get any of the other intermediate files generated by the HCP pipelines? In particular, the warpfields, jacobians, and affine matrices stored in T1w/xfms and MNINonLinear/xfms would be very helpful, since for many applications, I want to define ROIs in native space and then transform them into MNI/CIFTI space or vice/versa. These would also enable useful things like quickly regenerating the ACPC-aligned, distortion corrected anatomical images (T1w_acpc_dc/T2w_acpc_dc) from the original T1w/T2w data to check FreeSurfer's surface extraction and segmentation.

Thanks again! Looking forward to digging into the collection.
-Ely

**Comment by ericearl** [comment]
@elyb01 Terribly sorry for the long wait for you on this issue.  First, many thanks for asking for data exactly as directed in the documentation.  Second, let's try to answer your questions in the last paragraph there:

1. I believe we intentionally deleted many of the transforms as they were numerous small files taking up inordinate amounts of space and file handles on our servers (as you can imagine).  But I will check of your list what intermediary transform files, etc, we have.  Are there any that are more important to you than others?

2. I believe we mapped in the T1 and T2 volume files in our most recent upload.  [Read here](https://collection3165.readthedocs.io/en/stable/derivatives/#2-derivative-data-subsets-breakdown) and see if that might be what you want.
> `derivatives.anat.(T1w|T2w)`
> Anatomical imaging masked brain or full head in MNI space in a volume.
> `sub-#/ses-#/anat/sub-#_ses-#_(T1w|T2w)_space-MNI_(brain|head).nii.gz`

Let us know what else you need for your analyses and we will prioritize it for addition to the collection.

**Comment by rosemccollum** [comment]
@elyb01 Hope you're doing well, we are closing this comment but let us know if you need anything else from us!
