### ISSUE TITLE
questions regarding the parcellated functional timeseries

### ISSUE THREAD

**Issue by JunhongYu** [ABCD-STUDY/nda-abcd-collection-3165#30]
Not sure if i've understood this correctly, it appears from the data_subsets.txt file that only the timeseries data from subcortical regions are currently available? I'm wondering if the whole brain parcellated timeseries data is available somewhere?

I opened one of the parcellated dtseries.nii file in matlab and i got a 136 x1532 matrix. i presume this is the number of regions x number of timepoints? but 136 regions does seem somewhat strange for the subcortical regions

regarding the  Gordon2014 atlas — is this the same as the one described here https://academic.oup.com/cercor/article/26/1/288/2367115 and downloaded from https://sites.wustl.edu/petersenschlaggarlab/parcels-19cwpgu/ ?

**Comment by arueter1** [comment]
Hi @GerardYu - Thank you for your question! I am assigning this to some folks in our lab who can hopefully answer your questions. There may be a slight delay, but we will get to you as soon as we are able. Thanks!

**Comment by JunhongYu** [comment]
here's a related issue

i tried to read a Gordon2014FreeSurferSubcortical_desc-filtered_timeseries.ptseries.nii file using the "cifti" package in R, and it turns out to be a 352 x 1532 matrix. I presume the former number is the number of parcels and the latter is the number of timepoints. According to the atlas files here https://sites.wustl.edu/petersenschlaggarlab/parcels-19cwpgu/  the Gordon atlas only contains 333 parcels, so there seem to be an 'extra' 19 parcels in the Gordon2014FreeSurferSubcortical_desc-filtered_timeseries.ptseries.nii

is there some documentation on the Gordon atlas parcels used in the ABCC somewhere that i've missed?

**Comment by JunhongYu** [comment]
i realized the information i'm looking for is in the dlabel files

**Comment by ericearl** [comment]
@GerardYu For what it's worth, those are the 19 FreeSurfer Subcortical parcels, thus the name Gordon2014**FreeSurferSubcortical**.

Also documented here: https://collection3165.readthedocs.io/en/stable/pipeline/#4-dbp-generation-of-parcellated-timeseries-for-specific-atlases
