### ISSUE TITLE
How to know the number of time points for each run based on the concatenated time series.

### ISSUE THREAD

**Issue by ShuoranLi** [ABCD-STUDY/nda-abcd-collection-3165#32]
Hi there!
I'm interested in your parcellated time series, e.g., .*Yeo2011FreeSurferSubcortical_desc-filtered_timeseries.ptseries.nii. These time series are already concatenated for different runs. However, I want to separate the concatenated time series as different runs. I'm wondering if I can get to know the number of time points of each run just based on the concatenated data? Is this information somewhere inside the data? 
Thanks!

**Comment by ericfeczko** [comment]
Hi @ShuoranLi ,

The ptseries and dtseries files should contain the same number of frames.
One can always look at the metadata within the dtseries to know how many timepoints are available. This can be done by use of linux's "more" command (e.g. `more Yeo2011FreeSurferSubcortical_desc-filtered-timeseries.ptseries.nii. 

wb_command -nifti-information can be used to print the header as well to determine howq much data are in the concatenated timeseries file. 

Finally, one can view the executive summary for a given dataset to see how many frames may be in the concatenated as well.
