### ISSUE TITLE
Why the number of runs for some subjects less than ABCD Recommended dataset

### ISSUE THREAD

**Issue by ShuoranLi** [ABCD-STUDY/nda-abcd-collection-3165#33]
Hi there,
I'm wondering why the number of runs of processed baseline-year rs-fMRI for some subjects is **less than** that of ABCD 4.0 (passed DAIC quality control). Is that because you were using a different release? I understand why there are some missing subjects, but I'm not sure about missing runs.
Thanks!

**Comment by perronea** [comment]
@ShuoranLi The baseline data that is currently shared was from a prior QC version. We're in the process of updating the baseline data right now. I'll notify you here when the data has been shared on the NDA.

**Comment by ShuoranLi** [comment]
Thank you!
