### ISSUE TITLE
[req] document timeline and raw download hints

### ISSUE THREAD

**Issue by WillForan** [ABCD-STUDY/nda-abcd-collection-3165#35]
Thanks for providing a sane way to parse and subset ABCD data!

There are a few closed issues re. incorporating additional releases (#17, #26, #11). Is it feasible to add updates, progress, or outline blocking steps with rough time estimates to the readthedocs pages?

In the meantime, is there a place to find (or collect) hints on fetching a subset of raw imaging data from ndar releases?

**Comment by loj** [comment]
I would also be interested in an update/time estimate for when additional releases will be incorporated. The latest update that I found (https://github.com/ABCD-STUDY/nda-abcd-collection-3165/issues/26#issuecomment-1048218365) predicted a release for November of this year. Are things still on track for this?

Thanks! :-)

**Comment by LuciMoore** [comment]
@WillForan and @loj apologies for the delay - we are gearing up for a new release in the next few months!
