### ISSUE TITLE
motion.tsv files in year 2?

### ISSUE THREAD

**Issue by roscha** [ABCD-STUDY/nda-abcd-collection-3165#37]
Hi, 
Our lab recently downloaded the year 2 dataset and we weren't able to locate any motion trace files in the derivatives processed func data (/func/sub-*_ses-2YearFollowUpYArm1_task-*_run-*_desc-filtered_motion.tsv). The baseline year 1 have them and the doc does not seem to mentioned they are not supported anymore. Is it a download issue or a processing issue or could you help with locating the motion files?
Thanks

**Comment by audreymhoughton** [comment]
Hi @roscha ! The motion.tsv files do not currently exist for year 2. We will create them and upload them as soon as we can. Thank you for pointing this out!

**Comment by audreymhoughton** [comment]
@roscha when do you need these files by btw?

**Comment by roscha** [comment]
Hi @hough129 thank you for your message. I am currently working on year 2 data for a grant, so latest I could use the motion trace for this specific deadline would be mid-january. If that is not a reasonable time frame for your team, obviously then as soon as you can.

**Comment by audreymhoughton** [comment]
HI @roscha , Thank you for providing a clear deadline. Unfortunately, we may not be able to accommodate your request. We will update you as we upload the motion.tsv files and/or our timeline clarifies.

In the meantime, you could download the BIDS inputs and reprocess the data using the [newest release of the abcd-hcp-pipeline](https://github.com/DCAN-Labs/abcd-hcp-pipeline/tree/v0.1.2) to produce the motion.tsv files.

**Comment by LuciMoore** [comment]
@roscha I'm going to close this issue due to inactivity, but we will update our [release notes](https://collection3165.readthedocs.io/en/stable/release_notes/) once further data is uploaded
