### ISSUE TITLE
Clarification of specific files

### ISSUE THREAD

**Issue by aporter1350** [ABCD-STUDY/nda-abcd-collection-3165#38]
I am interested in using the concatenated functional dense time series data (sub-#/ses-#/func/sub-#_ses-#_task-(MID|nback|SST|rest)_bold_desc-filtered_timeseries.dtseries.nii) however before proceeding I was wondering if this file had been censored using filtered FD and if so is there more information regarding the threshold for censoring or is it simply the data right after stage 3 DBP Motion Censoring? I was also wondering if the interpolated frames are recensored following postprocesssing (as described in Power et al 2010). There is also a .mat file (sub-#/ses-#/func/sub-#_ses-#_task-(MID|nback|SST|rest)_desc-filtered_motion_mask.mat), is this mask created using fFD or FD? Thank you in advance for your time!

**Comment by ericfeczko** [comment]
Hey @aporter1350 !

We have updated our readthedocs with clearer information regarding the pipeline and motion censoring. As a reminder you can find it here!

https://collection3165.readthedocs.io/en/stable/pipelines/

You are correct that this is stage 3 DBP motion censoring. That being said the dtseries is complete; the dtseries for the interpolated frames with FD > 0.3 are included. Please use the .mat or tsv files to filter as appropriate thanks!
