### ISSUE TITLE
Is there a revised or new year 2 release timeline?

### ISSUE THREAD

**Issue by ericearl** [ABCD-STUDY/nda-abcd-collection-3165#42]
Hello former lab folks! I hope you all are doing well. I have a request for clarity that it appears many have asked before (and I was just asked too), but each has gotten a different response so I figured I'd refresh the question. I am not trying to give you a hard time or bother you, but I do want your GitHub repo here's dataset followers to know whatever the latest news is...

**When do you think the year 2 release might be available on NDA?** Or, as a potential alternative, do you have a data use agreement or data transfer agreement possible to share the large curated dataset pre-release from UMN instead? Previous questions here have been:

1. Feb 26, 2021: In #11 the anticipated release date was summer of 2021.
2. Jul 1, 2021: In #17 the answer was the soonest would be the fall of 2022.
3. Feb 17, 2022: In #26 the answer was somewhere between July and October 2022.
4. Nov 30, 2022: In #37 mentioned they *"downloaded the year 2 dataset and ... weren't able to locate any motion trace files in the derivatives"*. They went on to ask about availability by mid-January and were told *"[you] may not be able to accommodate [their] request"*.

I also noticed these two merged pull requests in the [release_notes.md](https://github.com/ABCD-STUDY/nda-abcd-collection-3165/blame/master/docs/release_notes.md#L35), so I'm hopeful for an upcoming release coming soon:

1. Feb 6, 2023: From #39
2. Feb 17, 2023: From #41

Thanks in advance for your response and good luck with getting the NDA QA process all done!

**Comment by ericfeczko** [comment]
Hey @ericearl !

We are currently working through the year 2 reprocessing. We've updated our documentation accordingly for anticipated timelines. As you well know, there are a lot of moving parts towards data processing, and we will make an announcement once we are ready for release :) 

https://collection3165.readthedocs.io/en/stable/

**Comment by bkossows** [comment]
Hi @ericfeczko,
I'm curious about the availability of the new release. Could you please inform me if you have plans to provide new data this autumn?
B.

**Comment by audreymhoughton** [comment]
@bkossows we are in the process of uploading data but were/are running into upload issues due to security changes by the NDA. We plan to update the documentation once the data is uploaded.
