### ISSUE TITLE
 missing subject baseline resting state data

### ISSUE THREAD

**Issue by aporter1350** [ABCD-STUDY/nda-abcd-collection-3165#43]
I have been working on a project that uses the abcd dataset and noticed that several (n=329) participants are missing baseline resting state time series data. I've attempted to download participants through NDA using minimally processed release 4.0 and through ABCC DCAN Labs. I reviewed the fastqc01 spreadsheet but did not see anything that would warrant them failing quality inspection. I was wondering if someone could help determine if this is an NDA issue or an issue with the resting state data. 

Particularly I am interested in the files that are located within this directory 
fmriresults01/derivatives/abcd-hcp-pipeline/sub-*/ses-baselineYear1Arm1/func/sub-
*_ses-baselineYear1Arm1_task-rest_bold_desc-filtered_timeseries.dtseries.nii

I have attached a csv file of the missing subjects. Let me know if you have any additional questions.

Thank you in advance for your time and consideration,
Alexis 
[abcd_missing_no_reason.csv](https://github.com/ABCD-STUDY/nda-abcd-collection-3165/files/11126201/abcd_missing_no_reason.csv)

**Comment by perronea** [comment]
Thank you for identifying this issue. I'll look into this missing data and prioritize getting it processed and uploaded asap.

**Comment by LuciMoore** [comment]
@aporter1350 I'm going to close this issue for now due to inactivity, but in case this still hasn't been resolved on your end, you can refer to the [Release Notes](https://collection3165.readthedocs.io/en/stable/release_notes/) for future announcements on when more/updated data is made available on the NDA
