### ISSUE TITLE
Is it possible to include 'family ID' in participants.tsv file in abcd-collection-3165?

### ISSUE THREAD

**Issue by wd-veloce** [ABCD-STUDY/nda-abcd-collection-3165#44]
Hi,

In Human Connectome Project (HCP), we could access family ids to specify which family each participant is from. It could help us to find which two participants are the twins and analyze heritability.

However in abcd-collection-3165 (or could we call it ABCC datasets?), we could only find participants.tsv file including participants' information. But no family IDs included. Meanwhile we could find this information in acspsw03.txt in the genetic data in abcd-collection-2573.

Is it possible to include family ID information in participants.tsv file in abcd-collection-3165? We believe it would not cause any privacy or personal identifying problems, since such information has already included in abcd-collection-2573. And it would be convenient for researchers who work on heritability analysis.

**Comment by ericfeczko** [comment]
Hey @wd-veloce !

We need to double-check to make sure, but if its ok we will plan to incorporate as a future enhancement -- I'll reply back here once its confirmed and then open an enhancement issue for the family ID.
