### ISSUE TITLE
Question on accessing ABCC imaging data

### ISSUE THREAD

**Issue by raphaelcuhk** [ABCD-STUDY/nda-abcd-collection-3165#45]
Dear experts,
when the NDA needs a gov log in, the imaging data could not be download anymore. I’ve tried different methods to download the latest imaging but still failed. Would you mind to tell me is there any way could I access the imaging data?
Thank you very much

**Comment by ericfeczko** [comment]
Hey @raphaelcuhk !

Apologies, for the late response. Our new downloader is available and can be used to access the imaging data, you can find it here:

https://github.com/DCAN-Labs/nda-abcd-s3-downloader

You may have a security issue with your NDA login -- if this has already been resolved feel free to ignore. I would contact the NDA helpdesk NDAHelp@mail.nih.gov to ensure that everything is ok.
