### ISSUE TITLE
issues with dcm2bids for sessions that passed QC

### ISSUE THREAD

**Issue by gsudre** [ABCD-STUDY/nda-abcd-collection-3165#49]
Hello,

I was wondering if you could help shed some light on these weird cases. I've been trying to process the ABCD DWI data for several subjects that pass DWI QC according to the tabular data, but when using the dcm2bids tools and the downloaded raw data they crash. Specifically, they crash during dcm2nii, and the error indicates that the sequence is not complete. 

Have you run into any issues like that? Or maybe the pipeline used to produce the tabular data ignores incomplete volumes? I'm happy to provide more details or a few examples.

Thanks!

**Comment by ericfeczko** [comment]
We have run into issues with one site where this has come up -- we're working on troubleshooting the issue -- I would recommend checking with the DAIRC as well as the data may be problematic on the NDA.

**Comment by audreymhoughton** [comment]
Hi @gsudre - we haven't been able to "solve" this issue with the data we've experienced the problem with. Our solution is to exclude the subjects with missing data. Did you reach out to the DAIRC? If so, what did they say?

**Comment by audreymhoughton** [comment]
I am going to close this issue, @gsudre ! Please re-open it if you are still running into problems.
