### ISSUE TITLE
Missing CIFTI files (e.g., dtseries) from the fMRIPrep outputs

### ISSUE THREAD

**Issue by narunpat** [ABCD-STUDY/nda-abcd-collection-3165#56]
We downloaded the fMRIPrep files frmo the ABCD Release 2.0.0, using fmriprep_data_subsets.txt from [https://github.com/DCAN-Labs/nda-abcd-s3-downloader/blob/main/fmriprep_data_subsets.txt](https://github.com/DCAN-Labs/nda-abcd-s3-downloader/blob/main/fmriprep_data_subsets.txt). 

We couldn't find CIFTI files, such as
```
sub-NDARINVXXXXXXXX_ses-baselineYear1Arm1_task-XXX_run-X_space-fsLR_den-91k_bold.dtseries.nii

sub-NDARINVXXXXXXXX_ses-baselineYear1Arm1_task-XXX_run-X_space-fsLR_den-91k_bold.json
```
We are a bit surprised by this given the flag --cifit-output was [used](https://collection3165.readthedocs.io/en/stable/pipelines/#fmriprep)

Here is a list of files we got from one of the tasks from one of the participants: 

```
sub-NDARINVXXXXXXXX_ses-baselineYear1Arm1_task-XXX_run-X_desc-confounds_timeseries.json

sub-NDARINVXXXXXXXX_ses-baselineYear1Arm1_task-XXX_run-X_desc-confounds_timeseries.tsv

sub-NDARINVXXXXXXXX_ses-baselineYear1Arm1_task-XXX_run-X_from-scanner_to-T1w_mode-image_xfm.txt

sub-NDARINVXXXXXXXX_ses-baselineYear1Arm1_task-XXX_run-X_from-T1w_to-scanner_mode-image_xfm.txt

sub-NDARINVXXXXXXXX_ses-baselineYear1Arm1_task-XXX_run-X_space-fsaverage5_hemi-L_bold.func.gii

sub-NDARINVXXXXXXXX_ses-baselineYear1Arm1_task-XXX_run-X_space-fsaverage5_hemi-R_bold.func.gii

sub-NDARINVXXXXXXXX_ses-baselineYear1Arm1_task-XXX_run-X_space-fsnative_hemi-L_bold.func.gii

sub-NDARINVXXXXXXXX_ses-baselineYear1Arm1_task-XXX_run-X_space-fsnative_hemi-R_bold.func.gii

sub-NDARINVXXXXXXXX_ses-baselineYear1Arm1_task-XXX_run-X_space-MNI152NLin2009cAsym_res-2_boldref.nii.gz

sub-NDARINVXXXXXXXX_ses-baselineYear1Arm1_task-XXX_run-X_space-MNI152NLin2009cAsym_res-2_desc-aparcaseg_dseg.nii.gz

sub-NDARINVXXXXXXXX_ses-baselineYear1Arm1_task-XXX_run-X_space-MNI152NLin2009cAsym_res-2_desc-aseg_dseg.nii.gz

sub-NDARINVXXXXXXXX_ses-baselineYear1Arm1_task-XXX_run-X_space-MNI152NLin2009cAsym_res-2_desc-aseg_dseg.nii.gz

sub-NDARINVXXXXXXXX_ses-baselineYear1Arm1_task-XXX_run-X_space-MNI152NLin2009cAsym_res-2_desc-brain_mask.nii.gz

sub-NDARINVXXXXXXXX_ses-baselineYear1Arm1_task-XXX_run-X_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.json

sub-NDARINVXXXXXXXX_ses-baselineYear1Arm1_task-XXX_run-X_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.nii.gz
```

**Comment by Shotgunosine** [comment]
@muet0005 was also looking for similar outputs. Just tagging them here to get the conversation in a single place. @narunpat and @muet0005, we've got those files for the fmriprep 20.2.0 run we did. Is that what you're looking for? I think the files may be fairly large, are there specific tasks you're interested in?

@ericfeczko, once we figure out exactly which files are needed, would it be ok for us to upload them to collection 3165?

**Comment by narunpat** [comment]
Thank you @Shotgunosine! Yes, we are looking for those  _den-91k_bold.dtseries.nii and _den-91k_bold.json files for every task and rest (just like all other fmriprepped data files). Appreciate your help here.

**Comment by ericfeczko** [comment]
Hey @Shotgunosine and @narunpat !

Thanks for reaching out :) We appreciate the catch that these files are missing. @Shotgunosine thanks for letting us know that you still have them :) If you can upload them to the collection, that would be fantastic, thanks! 

Please let us know how we can help -- we do have updated uploader tools and documentation that may help make things easier.

**Comment by LuciMoore** [comment]
@Shotgunosine I'm going to close this issue for now due to inactivity, but in case this still hasn't been resolved on your end, you can refer to the [Release Notes](https://collection3165.readthedocs.io/en/stable/release_notes/) for future announcements on when more/fixed data is made available

**Comment by ericearl** [comment]
@LuciMoore These data were uploaded by me and Dustin very recently, but the NDA has to do their QA process before they can be released.
