### ISSUE TITLE
Connectivity Matrix download

### ISSUE THREAD

**Issue by khalfinv** [ABCD-STUDY/nda-abcd-collection-3165#6]
Hi, 
I downloaded the Gordon atlas connecitvity matrices and noticed that some subjects does not have all the three types (5min, 10min and below threshold). 
Is it resonable in case the subject has less number of valid frames, e.g. do have a 5min matrix but not a 10min matrix. 
Can you please explain why would a subject have a 10min matrix but not a 5min matrix?

**Comment by ericearl** [comment]
@khalfinv Thanks for the question.  Not all subjects with a 5 minute matrix would have a 10 minute matrix due to either less "good" acquired data or less thresholded/censored data than 10 minutes.

@ericfeczko : I assume subjects with a 10 minute matrix would always have a 5 minute matrix.  Do you know of any reason why this might not be the case?

@khalfinv I am not sure if you are allowed by the NDA's Data Use Certification to publicly post NDAR pGUIDs online.  Please double-check your NDA ABCD Study DUC.

**Comment by khalfinv** [comment]
Thank you for your answer and comment. 
I deleted the pGuid.

**Comment by khalfinv** [comment]
Hi, after examine the downloaded data, I received 5956 subject with 10 minutes of scan and only 5578 with 5 minutes of scan. It doesn't seem really logical to me because as you said, subjects with 10 minutes scan supposed to have a 5 minute scan.

**Comment by ericearl** [comment]
@ericfeczko Have you had a chance to look into this answer?  I know you've been traveling, so not expecting an immediate response.

**Comment by ericfeczko** [comment]
Hi @khalfinv, 

My apologies for the late reply. I will need to double check, but I believe the remaining 378 subjects are simply missing. I'm examining the issue on our end, and should have an update for this issue by next friday.

**Comment by khalfinv** [comment]
Hi, @ericfeczko 
Did you manage to check it? 
I think that children who have 10 minute scan, supposed to have 5 minutes scan. Am I right? 
And logically it supposed to be more children with 5 minutes scan, than 10 minutes scan.

**Comment by ericfeczko** [comment]
My apogloies for the late reply. 
The 5 minute scans were generated for subjects with at least 10 minutes of good data, so there should be the same number for both. We should clarify in the documentation to make sure that this is the case. 

You are correct, there was a mistake where some subjects with 5 minutes of data were missing. I suspect an upload error, but I'm double-checking to make sure there isn't an error in reproducing the connectivity matrices themselves. Once I reproduce them, we should be able to fix this for the may release. I should be able to provide another update tomorrow.

**Comment by ericfeczko** [comment]
I was able to reproduce all but three matrices. The three failures appear to be related to the grid engine used, so an upload issue is likely the case. We can definitely fix this for May's release. 

My apologies again for the confusion from the documentation. We'll be sure to clarify it. Additionally, if you want us to include all possible 5 minute participants in the next release, please let us know.

**Comment by khalfinv** [comment]
Thank you for the replay. 
I decided to use only the 10 minute participants, so I will not need the 5 minute. 
Thank you

**Comment by ericearl** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Connectivity Matrix download](https://trello.com/c/TM88XPdv/11-connectivity-matrix-download)

**Comment by ericfeczko** [comment]
Hi @khalfinv, we have uploaded new connectivity matrices for 5 and 10 minute participants. This update should include the missing 5 minute participants you requested. The NDA is currently reviewing those uploads, and they should be released by the end of August -- according to their deadline.
