### ISSUE TITLE
requests.exceptions.HTTPError: 404 Client Error

### ISSUE THREAD

**Issue by yoyo9423** [ABCD-STUDY/nda-abcd-collection-3165#61]
Dear experts,

I'm sorry to disturb you. I met some problems when I tried to download the derivates from ABCC.
I used the code 'download.py -dp xxx -m xxx1.txt -o output -b xxx2.txt', and then input my NDA username according to the hint. But unluckily, I got the error:
requests.exceptions.HTTPError: 404 Client Error:  for url: https://nda.nih.gov/api/package/1220725/files

Could you please give me some suggestions to solve this problem? Many thanks!

**Comment by audreymhoughton** [comment]
Hi @yoyo9423 - we've been experiencing a similar issue. The NDA is working on getting it fixed, but I would suggest emailing their help desk to let them know your exact error and to stay in the loop!

**Comment by yoyo9423** [comment]
Thanks! I have contacted NDA help desk, and they  said that the ABCC_Downloader (which NDA does not maintain) appears to be using an old version of the nda-tools which utilizes a deprecated endpoint, which is where the error is being thrown. I have also tried the old version but it did not work. If you have any suggestions or updates, please let me know! Many Thanks!

**Comment by rosemccollum** [comment]
Hi @yoyo9423 
I have updated the requirements.txt to include the most recent version of nda-tools. Please try again with the new requirements.txt. I would also recommend creating a new package before you try again, just to be sure that this is not an error with your package. Please let us know if it works!

**Comment by yoyo9423** [comment]
Thanks so much! It works well with the updated requirements.txt.
