### ISSUE TITLE
systematically different T1w/T2w myelin ratios from Philips scanners

### ISSUE THREAD

**Issue by MarcinSzyWy** [ABCD-STUDY/nda-abcd-collection-3165#62]
Dear community,
With @bkossows  @Nencki Institute & Alethea de Jesus and Megan Herting @USC we are working on T1w/T2w myelin ratios from ABCD. bkossows has extracted tabulated data (D-K atlas mean parcelation) and now we are looking at the distribution of the T1w/T2w values. 

(see "Missing parcellation" thread here by bkossows  on how it was done).

We found that the values coming out the Philips scanners are systematically different ie <1 as opposed to values from Siemens and GE which are around 2 (see attached histogram, each data point is one subject's T1w/T2w value).

It could be a systematic difference and the Philips data could be perfectly usable, but it could be that the T1w/T2w ratios coming out of this scanner are flawed in some way. 
If you encountered this issue before, or if you have an idea how to check for the quality of the T1w/T2w from Philips, then we'd appreciate your input on that!
best, Marcin

![different myelin values coming out of different scanners](https://github.com/ABCD-STUDY/nda-abcd-collection-3165/assets/131356675/02f4222e-9cda-4e9b-8090-4b9e804fe0a2)

**Comment by LuciMoore** [comment]
Hello @MarcinSzyWy - apologies for the delay here. We have observed that the T1w and T2w myelin maps are not well-normalized, so it's not entirely surprising that there are batch effects from different acquisition sites. We haven't had a chance to look into this very deeply, but it's certainly an important issue and could make for a very useful paper if you are able to take a deeper dive!
