### ISSUE TITLE
Missing dMRI data

### ISSUE THREAD

**Issue by mattcieslak** [ABCD-STUDY/nda-abcd-collection-3165#63]
Hi! It appears that there are many dMRI scans missing from the baseline, 2_year and 4_year datasets. The baseline and 2_year (~4k each). Would it be helpful to share a list of missing IDs with you via secure channels?

**Comment by mattcieslak** [comment]
Tagging @ericfeczko and @hough129

**Comment by audreymhoughton** [comment]
@mattcieslak - you can send them via email to me! I frequently can't access box folders on Penn's side, so I think that will be the easiest option.

**Comment by mattcieslak** [comment]
sent!

**Comment by LuciMoore** [comment]
I believe this has been resolved
