### ISSUE TITLE
Cleanup Script Failed Due to changed file names

### ISSUE THREAD

**Issue by Noah-Baden** [ABCD-STUDY/nda-abcd-collection-3165#65]
I'm Noah Baden, the tech working with Dr. Dosenbach on copying ABCD Year 2 data over to our servers at Wash U, and we found an issue with the cleanup script used. It showed that the CustomClean script stopped working because the names of all the files were changed from task-**** to ses-2YearFollowUpYArm1_task-****, while the json did not make the same change. This left a lot of redundant files that would otherwise be cleaned, and has ballooned the space requirements for the dataset to over 2x the size actually necessary.

**Comment by audreymhoughton** [comment]
@Noah-Baden Hi, Noah! We are aware of the edits that need to be made to the CustomClean JSON. We haven't been able to prioritize fixing it yet, as it doesn't cause many issues for our team to have too many files on our system and processed outputs are always lower priority than the derivatives themselves. We will update you when we've had time to do the edits ourselves, but if you are in need of a fix sooner, you can make edits to [this JSON](https://github.com/DCAN-Labs/CustomClean/tree/main/examples) yourself to re-run CustomClean on your end! If you end up editing the JSON yourself, please add it to the repo for others to use.

**Comment by Noah-Baden** [comment]
@audreymhoughton I understand prioritizing other things, and we can deal with this ourselves, but it would have been easier on our end for those to get removed before transfer, to avoid either doubling transfer time, or having to curate the files we transfer.

**Comment by audreymhoughton** [comment]
@Noah-Baden I definitely get that - our team wasn't aware you were still transferring data, and we were unaware of the extra files issue until you pointed it out via email - thank you for that btw! We will let you know when we get around to the CustomClean JSON fix! :)

**Comment by madisoth** [comment]
Hi all, 

A CustomClean 2.0.3 pre-release is out now here: https://github.com/DCAN-Labs/CustomClean/releases/tag/v2.0.3

It has an updated JSON template for use with ABCD-BIDS 0.1.x outputs, and also fixes an issue where files would not be marked for removal when a `rel_path` in the JSON has `*` wildcards. Planning to include it in a future abcd-hcp-pipeline (ABCD-BIDS) release as well, after we fix a few omissions still in the JSON template and put it through some more testing.
