### ISSUE TITLE
Looking for Parcellated Functional Connectivity

### ISSUE THREAD

**Issue by Kricey** [ABCD-STUDY/nda-abcd-collection-3165#68]
Hi, I wonder if we are looking for parcellated functional connectivity of each participant, which files are correct? Since I have checked the `Gordon2014FreeSurferSubcortical_dparc.dlabel.nii`, seems no data inside. 
By the way, it seems that there are multiple versions of this file (as shown), what do the numbers after dparc.dlabel stand for？
<img width="581" alt="螢幕截圖 2024-02-26 上午11 32 42" src="https://github.com/ABCD-STUDY/nda-abcd-collection-3165/assets/160838862/c209e6ad-9f81-4764-a7c0-dad4cef14c6a">

**Comment by ericearl** [comment]
@Kricey Take a look at Issue #30 and see if that helps answer your question? I am guessing the picture above is either a bunch of little accidents or somehow an unpacked version of specific networks? I don't know how or when those `*_#.nii*` files appeared. But someone in DCAN-Labs should be able to answer that more fully. I'm guessing those `*.partial` files are incomplete downloads? Maybe check the size of each file?

**Comment by ericearl** [comment]
@Kricey For what it's worth, I couldn't reach the "Glasser 2014" parcellation web-link from [their paper](https://academic.oup.com/cercor/article/26/1/288/2367115) (which was actually published in 2016 by Cerebral Cortex), so I emailed Dr. Gordon and let him know. He said he will see what he can do to correct the paper's broken link with the publisher.

I did find [this](https://balsa.wustl.edu/WK71), if it might help, and Dr. Gordon said the Cortical Parcellation web-link is actually here now:

https://www.mir.wustl.edu/research/research-centers/neuroimaging/labs/egordon-lab/resources/

Good luck!

**Comment by ericfeczko** [comment]
Hey @Kricey !

The dlabel files are described in the derivatives section of the readthedocs. They are label files that correspond to each individual subject -- and contain no data themselves.


I would take a look at the list of available derivatives here:
https://collection3165.readthedocs.io/en/stable/derivatives/#parcellated-connectivity-derivativesfuncpconns

The pconns there are derived according to the ABCC manuscript, and referenced in the postprocessing section of the document -- they are 5 and 10 minutes.

https://collection3165.readthedocs.io/en/stable/postpipeline/

Additionally, pconns can be produced using the available outputs via multiple tools including BICEPS and cifti-connectivity, you can find recommendations here:

https://collection3165.readthedocs.io/en/stable/recommendations/
