### ISSUE TITLE
128 scan sessions with _task-rest_bold.nii.gz files

### ISSUE THREAD

**Issue by bryonmueller** [ABCD-STUDY/nda-abcd-collection-3165#7]
We downloaded the nda-3165 bids data in Sep, 2020. Of the 9647 scans with func directories, 128 have task-rest data files with the name sub-NDARINV????????_ses-baselineYear1Arm1_task-rest_bold.nii.gz. In all or most cases these scans have 383 volumes. These subjects are missing the task-rest .json files and do not have task-rest_run-0?_bold.nii.gz files. Some do have .json files for task fMRI data. At least some of these subjects have normal looking results in the derivatives directory tree.

**Comment by ericfeczko** [comment]
Hi Byron, 
Just to clarify, it sounds like the some of the input task-rest json and task-rest derived bold runs are missing, but the task data and the derivatives are sometimes normal, is that correct?

**Comment by ericearl** [comment]
@bryonmueller Was this resolved from our email conversation about how the runs 3 and 4 for resting state fMRI weren't shared yet?

I just double-checked and the NDA had told me these data were shared, but now I am not certain based on the NDA submission dashboard.  So I sent another question to the NDA Help desk.  I will check back here after I get a response as well.

**Comment by ericearl** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bryon M: 128 scan sessions with _task-rest_bold.nii.gz files](https://trello.com/c/FnnIXCFu/10-bryon-m-128-scan-sessions-with-task-restboldniigz-files)

**Comment by ericfeczko** [comment]
I think this is resolved for now, will close.
