### ISSUE TITLE
Derivatives surface.reg

### ISSUE THREAD

**Issue by andreaPay** [ABCD-STUDY/nda-abcd-collection-3165#70]
Dear DCAN Lab, 

Thank you for providing all these derivatives ! I would need some specific derivatives in order to answer my scientific questions. 

I would need : Surface white, cortical thickness, surface sphere, surface sphere .reg 

I imagine they are provided in this subset : 
derivatives.anat.T1w
derivatives.anat.T2w

I would like to confirm that I can find these derivatives in these subsets before downloading them. 

Best regards, 

Andréa Paysserand, Aix-Marseille University, France

**Comment by ericearl** [comment]
@andreaPay You can read all about which derivatives are in which data subsets here:

https://collection3165.readthedocs.io/en/stable/derivatives/

Enjoy!

**Comment by andreaPay** [comment]
Thank you a lot for your answer. However, I already red the documentation, and I see no infromation regarding what is provided in the derivatives.anat.T1w and derivatives.anat.T2w subsets, which are possible subsets to download when opening the datausubset text file. I only see information regarding others subsets, but can't see what is inside these ones.

**Comment by ericearl** [comment]
@andreaPay Thank you for re-iterating and sorry to make you do that. I assumed it would be covered on that page and I was wrong.

A closer look seems to suggest those won't work at all:

https://github.com/DCAN-Labs/nda-abcd-s3-downloader/blob/main/src/Downloader.py#L205-L223

The "basenames" from the `data_subsets.txt` file seem to be used to build the exact "manifest" JSON file names:

`manifest = sub + '.' + base + '.manifest.json'`

I suspect it was one of those intended features to add to the software that never happened. It's probably better/safer to just list the complete data subsets you want by their exact names listed in the readthedocs page.

**Comment by ericfeczko** [comment]
Hey Andrea,

Unfortunately, we don't provide the surface and sphere reg files. These are used for performing the surface-based projection, and are cleaned for space reasons (every 1 MB of data = 10GB across the whole dataset!). We also don't provide the white and pial surfaces, though the midthickness surface is available under multiple spaces. 

If it helps, the cortical thickness dscalar is provided in a standard fsLR32k space, and all ABCC cortical thickness data can be analyzed without performing any needed registrations. 

Hope this helps!

**Comment by andreaPay** [comment]
Thank you a lot @ericearl and @ericfeczko for your answers ! 
I shall probably download the minimally processed image provided by ABCD and run freesurfer to get the derivatives I need for my analysis. I thank you a lot for your answers ! I wish you the best in your neuroscientific journey !
