### ISSUE TITLE
Participants.tsv appears to not be fully accurate regarding scanner platform

### ISSUE THREAD

**Issue by mharms** [ABCD-STUDY/nda-abcd-collection-3165#8]
According to the `participants.tsv`, there are 6 Philips sites, when there should only be 3.  

Sites 01, 17 and 19 are all legit Philips sites.  But sites 02, 06 and 11 each have 1-2 participants associated with them as "Philips" as well.

Some quick poking around identifies subjects at other sites that are misattributed to the wrong scanner platform as well.  (Or alternatively, the site label is incorrect for these participants).

**Comment by ericearl** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Upload updated participants.tsv and update readthedocs](https://trello.com/c/kErTBnwo/12-upload-updated-participantstsv-and-update-readthedocs)

**Comment by LuciMoore** [comment]
@mharms I'm going to close this due to inactivity, but we are going to double check on our end that this problem doesn't persist in the most current release 5 tabulated data available on the NDA
